export default [
  {
    en: ['Spoke at Open Building Council', 'Los Angeles'],
    kr: ['로스엔젤레스 오픈빌딩 학회 발표'],
    active: false,
    icon: 'business',
    year: 2018,
  },
  {
    en: ['USC Student Housing'],
    kr: ['USC 기숙사 프로젝트'],
    active: false,
    icon: 'business',
    year: 2019,
  },
  {
    kr: ['패스트파이브 MOU 체결', '런던클럽 MOU 체결'],
    en: ['MOU with Fastfive', 'MOU with London Club'],
    active: true,
    icon: 'question_answer',
    year: 2020,
  },
  {
    kr: ['한양대 캠퍼스타운', '창업경진대회 수상'],
    en: ['HY Campustown Startup Competition Winner'],
    active: false,
    icon: 'emoji_events',
    year: 2020,
  },
  {
    kr: ['3개 벤처투자사 시드투자유치'],
    en: [
      'Raised Seed Funding',
      'BLUEPOINT PARTNERS',
      'KRYPTON',
      'PLAN. H VENTURES',
    ],
    active: true,
    icon: 'paid',
    year: 2020,
  },
  {
    kr: ['LH 공공데이터 창업경진대회 장려상'],
    en: ['Honorable Mention at LH Public Data Startup Competition'],
    active: false,
    icon: 'emoji_events',
    year: 2020,
  },
  {
    kr: ['하반기 데이터바우처 우선협상자 선정'],
    en: ['Won AI Voucher at K-Data'],
    active: true,
    icon: 'emoji_events',
    year: 2020,
  },
  {
    kr: ['한림건축 MOU 체결'],
    en: ['MOU with Hanlim Architecture Group'],
    active: true,
    icon: 'question_answer',
    year: 2020,
  },
  {
    kr: ['TRYEVERYTHING', '100개사 선정'],
    en: ['Selected for TryEverything 100 Startups'],
    active: false,
    icon: 'emoji_events',
    year: 2020,
  },
  {
    kr: ['컴업 2020 루키리그', '36개사 선정'],
    en: ['Selected for Comeup2020 36 Startups'],
    active: false,
    icon: 'emoji_events',
    year: 2020,
  },
  {
    kr: ['팁스 R&D 9월 기업 선정'],
    en: ['Won TIPS R&D Fund'],
    active: false,
    icon: 'paid',
    year: 2020,
  },
  {
    kr: ['혁신기술공모전 우수상'],
    en: ['Third-tier prize at Innovative Technology Competition'],
    active: false,
    icon: 'emoji_events',
    year: 2020,
  },
  {
    kr: ['K - 비대면 바우처 기업 선정', '창업 진흥원'],
    en: ['Won K-untact Voucher'],
    active: false,
    icon: 'paid',
    year: 2020,
  },
  {
    kr: ['IBK창공 마포 6기 선정'],
    en: ['Selected for IBK Accelerator Program'],
    active: false,
    icon: 'emoji_events',
    year: 2020,
  },
  {
    kr: ['신영그룹 컨설팅 계약 체결'],
    en: ['Selected for US Startup Voucher'],
    active: false,
    icon: 'emoji_events',
    year: 2021,
  },
  {
    kr: ['스타트업 해외진출 바우처 선정'],
    en: ['Signed Consulting Contract with ShinYoung'],
    active: false,
    icon: 'emoji_events',
    year: 2021,
  },
  {
    kr: ['신한퓨처스랩, ‘프롭테크 게임체인저’ 공모전 대상'],
    en: ['Shinhan Futures Lab, "Proptech Gaming Tinger" Grand Prize'],
    active: false,
    icon: 'emoji_events',
    year: 2021,
  },
  {
    kr: ['40억 투자 유치'],
    en: ['Attracted 4 billion investment'],
    active: false,
    icon: 'emoji_events',
    year: 2021,
  },
  {
    kr: ['네오밸류로부터 투자 유치'],
    en: ['Attracted  investment from NeoValue'],
    active: false,
    icon: 'emoji_events',
    year: 2022,
  },
  {
    kr: ['Korea AI Startup 100 선정'],
    en: ['Selected for Korea AI Startup 100'],
    active: false,
    icon: 'emoji_events',
    year: 2022,
  },
  {
    kr: ['Z-maps LA 지역 출시'],
    en: ['Launched Z-maps for LA County'],
    active: false,
    icon: 'business',
    year: 2023,
  },
  {
    kr: ['SoLa Impact 와 전략적 파트너십 체결'],
    en: ['Entered into a strategic partnership with SoLa Impact'],
    active: false,
    icon: 'question_answer',
    year: 2023,
  },
  {
    kr: ['구글 여성 파운더스 펀드 선정'],
    en: ['Selected for Google Women Founders Fund'],
    active: false,
    icon: 'emoji_events',
    year: 2023,
  },
]
