<template>
  <div id="fullpage-private">
    <div class="section section-privacy-policy">
      <div class="section-inner">
        <div class="inner-contents">
          <h1>Privacy Policy of Zenerate Inc.</h1>
          <p>
            <strong
              >Last updated 11/16/2023. For a prior version of our Privacy
              Policy, click
              <a href="https://www.zenerate.ai/privacy-policy-11292021">here</a
              >.</strong
            >
          </p>
          <p>
            Thank You for choosing to be part of our community at Zenerate Inc.
            (The “Company”, “we”, “us”, or “our”). We are committed to
            protecting Your Personal Information and Your right to privacy. This
            Privacy Policy (“Privacy Policy”) is designed to help You understand
            what information we collect, why we collect such information and how
            we use it. If You have any questions or concerns about this privacy
            notice or our practices with regards to Your Personal Information,
            please contact us at
            <a href="mailto:contact@zenerate.ai">contact@zenerate.ai</a>.
          </p>
          <p>
            By visiting, accessing or using the Internet site located at
            <a href="https://zenerate.ai/">https://zenerate.ai/</a>, (the
            “Site”) or any services provided in connection with the Site
            including but not limited to any other corresponding domains, media
            form, media channel, website or mobile application related, linked,
            or otherwise connected thereto (collectively, the “Service” ),
            including but not limited to
            <a href="https://zmaps.ai">https://zmaps.ai</a>,
            <a href="https://app.zenerate.ai">https://app.zenerate.ai</a> and
            <a href="https://modular.zenerate.ai">https://modular.zenerate.ai</a
            >, You agree that Your information, including Your Personal
            Information, will be handled as described in this Privacy Policy,
            which is incorporated by reference into our Terms and Conditions [<a
              href="https://www.zenerate.ai/terms-and-conditions"
              >LINK</a
            >].
          </p>

          <h2>1. Interpretation and Definitions</h2>
          <h3>Interpretation</h3>
          <p>
            The words of which the initial letter is capitalized have meanings
            defined under the following conditions. The following definitions
            shall have the same meaning regardless of whether they appear in
            singular or in plural.
          </p>
          <h3>Definitions</h3>
          <p>For the purposes of this Privacy Policy:</p>
          <ul>
            <li>
              <strong>You</strong> means the individual accessing or using the
              Site or Service, a corporation, or other legal entity on behalf of
              which such individual is accessing or using the Service, as
              applicable.
            </li>
            <li>
              <strong>Account</strong> means a unique account created for You to
              access our Service or parts of our Service.
            </li>
            <li>
              <strong>Company</strong> refers to Zenerate Inc., a Delaware
              corporation, located at 222 N Pacific Coast Hwy F 10, El Segundo,
              CA 90245.
            </li>
            <li>
              <strong>Cookies</strong> are small files that are placed on Your
              computer, mobile device or any other device by a website,
              containing the details of Your browsing history on that website
              among its many uses.
            </li>
            <li>
              <strong>Device</strong> means any device that can access the
              Service such as a computer, a mobile device or a digital tablet.
            </li>
            <li>
              <strong>Personal Information</strong> is any information that
              relates to an identified or identifiable individual.
            </li>
            <li>
              <strong>Service</strong> efers to any other related services
              provided by Zenerate Inc through the Site, including but not
              limited to <a href="https://zmaps.ai">https://zmaps.ai</a>,
              <a href="https://app.zenerate.ai">https://app.zenerate.ai</a> and
              <a href="https://modular.zenerate.ai"
                >https://modular.zenerate.ai</a
              >
            </li>
            <li>
              <strong>Usage Data</strong> refers to data collected
              automatically, either generated by the use of the Service or from
              the Site or the Service infrastructure itself (for example, the
              duration of a page visit).
            </li>
          </ul>

          <h2>2. INFORMATION WE COLLECT</h2>
          <h3>2.1 Personal Information</h3>
          <p>
            We collect information that You provide us. While using our Service,
            we may ask You to provide Us with certain personally identifiable
            information that can be used to contact or identify You. When You
            use our Service or associated tools, we may collect the following
            kinds of Personal Information from You personally identifiable
            information may include, but is not limited to:
          </p>
          <ul>
            <li>
              Information You provide to us when You register Your account
            </li>
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Username</li>
            <li>Password</li>
            <li>Account ID</li>
            <li>Information You provided on Your profile</li>
            <li>Your company or employer name</li>
            <li>Your Job Title</li>
            <li>Usage Data</li>
            <li>
              Usage Data is collected automatically when using the Service
            </li>
            <li>
              Telephone number, and business, and billing addresses (including
              street and postal code)
            </li>
            <li>
              Payment information such as payment card number, expiration date,
              billing address, and financial account number
            </li>
            <li>Birth date and gender</li>
            <li>Geolocation</li>
            <li>
              Social media account ID and other publicly available information
            </li>
            <li>
              Other communications that occur through the Service among users
            </li>
            <li>The searches and transactions conducted through the Service</li>
            <li>Other interactions with You on our online services</li>
          </ul>

          <h3>2.2 Usage Data</h3>
          <p>
            When You use our Service, we may automatically collect the following
            types of information from You or Your devices.
          </p>
          <ul>
            <li>Your Device's Internet Protocol address (e.g. IP address)</li>
            <li>Your device type</li>
            <li>Unique device identification numbers</li>
            <li>Browser type</li>
            <li>Browser version</li>
            <li>Operating system</li>
            <li>
              How our device has interacted with our Services including the
              pages of our Service that You visit ,the time and date of Your
              visit, the time spent on those pages
            </li>
            <li>
              Details of any referring websites or exit pages, as well as
              general geographic location
            </li>
            <li>Other diagnostic data</li>
            <li>
              Information Your browser sends whenever You visit our Service or
              when You access the Service by or through a mobile device
            </li>
          </ul>

          <h3>2.3 Tracking Technologies and Cookies</h3>
          <p>
            We use Cookies and similar tracking technologies to track the
            activity on our Service and store certain information. Tracking
            technologies used are tags, and scripts to collect and track
            information and to improve and analyze our Service. The technologies
            we use may include:
          </p>
          <ul>
            <li>
              <strong>Managing Cookies or Browser Cookies.</strong> A cookie is
              a small file placed on Your Device. You can instruct Your browser
              to refuse all Cookies or to indicate when a Cookie is being sent.
              However, if You do not accept Cookies, You may not be able to use
              some parts of our Service. Unless You have adjusted Your browser
              setting so that it will refuse Cookies, our Service may use
              Cookies.
            </li>
          </ul>
          <p>
            Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies
            remain on Your personal computer or mobile device when You go
            offline, while Session Cookies are deleted as soon as You close Your
            web browser. This type of information is collected to make the Site
            more useful to You and to tailor the experience with us to meet Your
            special interests and needs.
          </p>

          <h2>3. HOW DO WE USE PERSONAL INFORMATION</h2>
          <h3>3.1 Why We Collect Your Personal Information</h3>
          <p>
            We may use the information we collected from You for the following
            purposes:
          </p>
          <ul>
            <li>
              <strong>To provide and maintain our Service</strong>, including to
              improve and monitor the usage of our Service.
            </li>
            <li>
              <strong>To manage Your Account</strong>: to manage Your
              registration as a user of the Service. The Personal data You
              provide can give You access to different functionalities of the
              Service that are available to You as a registered user.
            </li>
            <li>
              <strong>For the performance of a contract</strong>: the
              development, compliance and undertaking of the purchase contract
              for the products, items or services You have purchased or of any
              other contract with us through the Service.
            </li>
            <li>
              <strong>To contact You</strong>: To contact You by email,
              telephone calls, SMS, or other equivalent forms of electronic
              communication, such as a mobile application's push notifications
              regarding updates or informative communications related to the
              functionalities, products or contracted services, including the
              security updates, when necessary or reasonable for their
              implementation.
            </li>
            <li>
              <strong>To provide You</strong> with news, special offers and
              general information about other goods, services and events which
              we offer that are similar to those that You have already purchased
              or enquired about unless You have opted not to receive such
              information.
            </li>
            <li>
              <strong>To manage Your requests</strong> To attend and manage Your
              requests to us.
            </li>
            <li>
              <strong>For business transfers</strong>: We may use Your
              information to evaluate or conduct a merger, divestiture,
              restructuring, reorganization, dissolution, or other sale or
              transfer of some or all of our assets, whether as a going concern
              or as part of bankruptcy, liquidation, or similar proceeding, in
              which Personal data held by us about our Service users is among
              the assets transferred.
            </li>
            <li>
              <strong>For other purposes</strong>: We may use Your information
              for other purposes, such as data analysis, identifying usage
              trends, determining the effectiveness of our promotional campaigns
              and to evaluate and improve our Service, products, services,
              marketing and Your experience.
            </li>
          </ul>

          <h3>3.2 Sharing Your Personal Information</h3>
          <p>
            The Company may process of share Your data that we hold based on the
            following legal basis: More specifically, we may need to process
            Your data or share Your Personal Information in the following
            situations:
          </p>
          <ul>
            <li>
              <strong>Business Transfers</strong> We may share or transfer Your
              information in connection with, or during negotiations of, any
              merger, sale of company assets, financing, or acquisition of all
              or a portion of our business to another company.
            </li>
            <li>
              <strong>Affiliates</strong> We may share Your information with our
              affiliates, in which case we will require those affiliates to
              honor this privacy notice. Affiliates include our parent company
              and any subsidiaries, joint venture partners or other companies
              that we control or that are under common control with us. Your
              Personal Information may be stored and processed in any country
              where we have facilities, and by using the Services, You consent
              to the transfer of Your Personal Information to countries,
              including the Republic of Korea, which may be outside of Your
              country of residence and may provide for different and less
              stringent data protection rules than in Your country. If You
              object to Your Personal Information being transferred or used as
              described in this Privacy Policy, please do not use any of our
              Services and immediately delete all Personal Information from the
              Services.
            </li>
            <li>
              <strong>Business Partners</strong> We may share Your information
              with our business partners to offer You certain products, services
              or promotions.
            </li>
            <li>
              <strong>Agents</strong> We may employ or enter into a business
              contract with other companies and people to perform tasks on our
              behalf (“Agents”) - meaning they are helping us provide our
              Services. We may share Your data with such Agents solely as
              necessary for them to help us provide our Services. Unless we tell
              You differently, our Agents do not have any right to use data we
              share with them beyond what is necessary to assist us.
            </li>
            <li>
              We use a third-party credit card processing provider to manage
              credit card and ACH processing.
            </li>
            <li>
              We use a third-party analytics tool provider to understand how
              users interact with our Service.
            </li>
            <li>
              We use a third-party marketing service provider to contact and
              attract new users. To understand the target users, we may share
              the data with the marketing service provider.
            </li>
            <li>
              <strong>Legal rights and obligations</strong>. We may disclose
              Your Personal Information and associated records to enforce our
              policies; as necessary to satisfy our tax or other regulatory
              reporting requirements, including the remission of certain taxes
              in the course of processing payments; or where we are permitted
              (or believe in good faith that we are required) to do so by
              applicable law, such as in response to a subpoena or other legal
              request, in connection with actual or proposed litigation, or to
              protect and defend our property, people and other rights or
              interests.
            </li>
            <li>
              <strong>Law Enforcement</strong>. We may release data when we
              believe in good faith that release is necessary to comply with the
              law, enforce or apply our conditions of use and other agreements,
              protect the rights, property, or safety of our employees, our
              users, or others. Please note that we may be required to release
              the personal data of EU individuals in response to lawful requests
              from public authorities including to meet national security and
              law enforcement requirements. If Your data request draws attention
              to an ongoing violation of our Terms and Conditions or other
              agreement, we will take action to prevent further abuse, including
              actions that may notify the user that we are aware of their
              misconduct.
            </li>
            <li>
              We may receive orders, subpoenas or other legal demands for
              Personal Information that has been collected on behalf of third
              party providers integrated with us through the use of their
              applications or services. In such cases, we will refer the party
              requesting the Personal Information to the applicable third-party
              provider. That provider will respond in accordance with its own
              policies and may disclose Your Personal Information in response to
              such subpoena or other demand for information. If You have
              questions about any such disclosures, You should contact the
              applicable provider directly, as we are not responsible for the
              policies and practices of such third-party providers. We will have
              no liability in connection with any act or omission of any such
              provider with respect to Your data or information or otherwise.
            </li>
            <li>
              <strong>To Other Third Parties</strong>. We also may disclose the
              information we collect from You to other third parties with Your
              consent or upon Your consent.
            </li>
          </ul>

          <p>
            We do not sell Your Personal Information for the intents and
            purposes of the California Consumer Privacy Act (CCPA).
          </p>

          <h2>4. THIRD-PARTY LINKS</h2>
          <p>
            Our Service may contain links to third-party websites and online
            services. Any access to and use of such linked websites is not
            governed by this Privacy Policy, but, instead, is governed by the
            privacy policies of those third-party websites. The inclusion of a
            link or accessibility of third-party websites does not imply
            endorsement of such third party websites by us. We are not
            responsible for the information practices of such third-party
            websites.
          </p>

          <h2>5. THE SECURITY OF YOUR INFORMATION</h2>
          <p>
            We have implemented commercially reasonable precautions, including,
            where appropriate, password protection and encryption to protect our
            Service the information we collect from loss, misuse, and
            unauthorized access, disclosure, alteration, and destruction. Please
            be aware that despite our best efforts, no data security measures
            can guarantee 100% security all the time.
          </p>
          <p>
            You should take steps to protect against unauthorized access to Your
            password, computer, and web-enabled devices, among other things, by
            signing off after using a shared computer, inserting a password on
            Your web-enabled device, choosing a password that nobody else knows
            or can easily guess, and keeping Your password private. You should
            never share Your log-in information with others. We are not
            responsible for any lost, stolen or compromised passwords, or for
            any activity on Your account via unauthorized password activity.
          </p>

          <h3>Data Subject Rights</h3>
          <p>
            You have rights concerning Your personal data. For all such Personal
            data, You may exercise Your rights by contacting us as stated below.
            If You wish to exercise Your privacy rights under applicable law
            (including the EU or UK GDPR or the California Consumer Privacy Act
            (CCPA)), such as the right to request access to, rectification or
            erasure of Your personal data held with us, or to restrict or object
            to such personal data's processing, or to obtain a copy or port such
            personal data (each to the extent available to You under the laws
            which apply to You) - please contact us by e-mail at
            <a href="mailto:contact@zenerate.ai">contact@zenerate.ai</a>.
          </p>

          <h3>California Civil Code</h3>
          <p>
            Under California Civil Code Sections 1798.83-1798.84, California
            residents are entitled to ask us for a notice identifying the
            categories of Personal Information which we share with our
            affiliates and/or third parties for marketing purposes and providing
            contact information for such affiliates and/or third parties. If You
            are a California resident and would like a copy of this notice,
            please submit a written request to
            <a href="mailto:contact@zenerate.ai">contact@zenerate.ai</a>
          </p>

          <h2>6. Children</h2>
          <p>
            Our Service does not address anyone under the age of 13. If You are
            a child under 13, please do not attempt to register on the Services
            or send any Personal Information about Yourself to us. We do not
            knowingly collect personally identifiable information from anyone
            under the age of 13. If You are a parent or guardian and You are
            aware that Your child has provided us with Personal data, please
            contact us. If we become aware that we have collected Personal data
            from anyone under the age of 13 without verification of parental
            consent, we take steps to remove that information from our servers.
          </p>
          <p>
            If we need to rely on consent as a legal basis for processing Your
            information and Your country requires consent from a parent, We may
            require Your parent's consent before We collect and use that
            information.
          </p>

          <h2>7. Other Users With Whom You Share Your Information</h2>
          <p>
            We cannot control the actions of other users with whom You share
            Your information. We cannot, and do not, control the information You
            share with other users using the Services, or how such other users
            will use or share such information. For example, if You share Your
            information via forums, blogs, or dashboards where other users may
            have access to such information, we are not responsible for other
            users using such information. Also, if You share information with
            other users by using the Services such as message function or chat,
            we do not control the information You share with other users or how
            such other uses will use or share such information. We are not
            liable for such shared information with other users.
          </p>

          <h2>8. Accessing and Correcting Your Personal Information</h2>
          <p>
            You have the right to access, correct or delete Your Personal
            Information including Contact Information or billing Information You
            provided us. You may access Your Personal Information by logging
            into Your account and making necessary changes. Or You may request
            such changes to Your account by sending an e-mail to
            <a href="mailto:contact@zenerate.ai">contact@zenerate.ai</a> For
            other Personal Information not modifiable through Your account,
            including but not limited to email, please email us at
            <a href="mailto:contact@zenerate.ai">contact@zenerate.ai</a>. We
            will try to comply with Your request as soon as and to the extent to
            which it is reasonably practicable. We may not accommodate the
            request to change Your Personal Information if we believe the change
            would violate any law of legal requirement, cause the information to
            be incorrect, or if doing so would be burdensome in our discretion.
            Please note that copies of information that You have updated,
            modified or deleted may continue to reside in our systems for a
            period of time.
          </p>

          <h2>9. Your Choices</h2>
          <p>
            From time to time, we may send You emails offering products and
            services that we believe might be of interest to You. If, at any
            time, You would like to stop receiving these emails, please follow
            the opt-out instructions contained in any such e-mail or request the
            opt-out option by sending us an email to
            <a href="mailto:contact@zenerate.ai">contact@zenerate.ai</a>. Please
            note that it may take some time for us to process the opt-out
            requests, and that Your opt-out pertains only to the receipt of
            marketing and advertising promotions and not for issues related to
            Your service. If You opt-out, we will still send You emails for
            service purposes, such as for communications about Your account,
            responses to Your requests, administrative messages.
          </p>
          <p>
            Do-Not-Track Signals and Similar Mechanisms: The Site of the Service
            does not respond to Do Not Track signals.
          </p>

          <h2>10. Retention Period</h2>
          <p>
            We may keep Your information for as long as we deem it necessary for
            our business purposes, or as otherwise required to operate the
            Service, comply with Your requests, or comply with applicable law.
            We will retain Your information for the period necessary to fulfill
            the purposes outlined in this Privacy Policy unless a longer
            retention period is required or allowed by law. Your information may
            or may not be encrypted while stored or archived by us.
          </p>

          <h2>11. Change</h2>
          <p>
            We may amend this Privacy Policy from time to time. Use of
            information we collect now is subject to the Privacy Policy in
            effect at the time such information is used. If we make any material
            changes to this Privacy Policy, we will provide notice of such
            changes through a posting on the Site or through another reasonable
            means of communication. You are bound by any changes to the Privacy
            Policy when You use the Services after such notice has been
            provided. Therefore, we encourage You to check the date of this
            Privacy Policy whenever You access or use the Services to check if
            this Privacy Policy has been updated. You must review this Privacy
            Policy on a regular basis to keep Yourself apprised of any changes.
            If You do not agree to any modifications to this Policy, Your sole
            recourse is to immediately stop all use of the Services. Your
            continued use of any Services following the posting of any
            modifications to this Privacy Policy will constitute Your acceptance
            of the revised Privacy Policy. Should You have any questions
            regarding this Privacy Policy, please contact us at the contact
            information listed at the end of this Privacy Policy. Please note
            that none of our employees or agents has the authority to vary any
            of our Privacy Policies.
          </p>

          <h2>12. Contact Us</h2>
          <p>
            If You have any questions or concerns regarding our privacy policy,
            please contact us at
            <a href="mailto:contact@zenerate.ai">contact@zenerate.ai</a> or at
            222 N Pacific Coast Hwy F 10, El Segundo, CA 90245.
          </p>
        </div>
      </div>

      <i class="scroll-to-top" @click="($evt) => scollToTop()">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
          fill="#000000"
        >
          <path d="M0 0h24v24H0V0z" fill="none" />
          <path
            d="M4 12l1.41 1.41L11 7.83V20h2V7.83l5.58 5.59L20 12l-8-8-8 8z"
          />
        </svg>
      </i>

      <div class="section section-footer fp-auto-height-responsive">
        <Footer></Footer>
      </div>
    </div>
  </div>
</template>
<script lang="ts" setup>
import { ref, onMounted, onBeforeUnmount, computed } from 'vue'
import Store from '/Store/index'
import Footer from '/Components/Footer.vue'

const fullpage = computed(() => Store.state.root.FullPage)

onMounted(() => {
  fullpage.value.destroy()
})

const scollToTop = () => {
  const el = document.querySelector('.inner-contents')
  el.scrollIntoView({ behavior: 'smooth', block: 'start' })
}
</script>
<style lang="scss" scoped>
#fullpage-private {
  overflow: hidden;
  .section-inner {
    @include flex;
    position: relative;
    height: 100%;
    padding: 0px 60px;
    cursor: default;

    @include en-tablet {
      padding: 0px 24px;
      max-width: 100%;
    }
    @include en-mobile {
      padding: 0 24px;
      max-width: 100%;
    }
  }
}

.scroll-to-top {
  @include fixed(bottom 24px right 32px);
  cursor: pointer;
  z-index: 9;

  svg {
    width: 40px;
    height: 40px;

    fill: $text-darken;
  }

  @include en-mobile {
    @include fixed(bottom 14px right 18px);
    svg {
      width: 32px;
      height: 32px;
    }
  }
}

.inner-contents {
  padding-top: 140px;
  padding-bottom: 60px;
  height: content-fit;
  text-align: left;
}

h1 {
  @include medium(36);
  margin: 0px 0px 48px 0px;
  padding: 0px;
  color: #161616;
  @include en-mobile {
    @include medium(28);
    margin: 0px 0px 28px 0px;
  }
}

h2 {
  @include bold(22);
  margin: 0px 0px 28px 0px;
  padding: 0px;
  color: #161616;
  @include en-mobile {
    @include bold(18);
    margin: 0px 0px 16px 0px;
  }
}

h3 {
  @include bold(18);
  margin: 0px 0px 28px 0px;
  padding: 0px;
  color: #161616;
  @include en-mobile {
    @include bold(16);
    margin: 0px 0px 16px 0px;
  }
}

ul {
  margin-bottom: 28px;
  @include en-mobile {
    margin-bottom: 16px;
  }

  li {
    @include regular(16);
    margin: 0px 0px 14px 20px;
    list-style-type: disc;
    color: #707070;

    @include en-mobile {
      @include regular(14);
      margin: 0px 0px 12px 16px;
    }
  }
}

p {
  @include regular(16);
  margin-bottom: 20px;
  line-height: 20px;
  color: #707070;
  @include en-mobile {
    @include regular(14);
    margin: 0px 0px 16px 0px;
  }
}

span {
  display: block;
  margin-bottom: 4px;

  &.core-text {
    color: #5c6dff;
  }
}

a,
a:hover,
a:active,
a:visited {
  text-decoration: underline;
  color: #5c6dff;
}
</style>
