<template>
  <div id="fullpage-private">
    <div class="section section-privacy-policy">
      <div class="section-inner">
        <div class="inner-contents">
          <h1>Privacy Policy of Zenerate Inc.</h1>
          <p><strong>Last updated 11/29/2021</strong></p>
          <p>
            Thank you for choosing to be part of our community at Zenerate Inc.
            (“The Company”, “We”, “Us”, or “Our”). We are committed to
            protecting your personal information and your right to privacy. If
            you have any questions or concerns about this privacy notice or our
            practices with regard to your personal information, please contact
            us at contact@zenerate.ai.
          </p>
          <p>
            By using the services provided by Zenerate Inc, any other related
            services, or using our website at http://zenerate.ai/, you accept
            the practices outlined in this Privacy Policy.
          </p>

          <h2>Interpretation and Definitions</h2>
          <h3>Interpretation</h3>
          <p>
            The words of which the initial letter is capitalized have meanings
            defined under the following conditions. The following definitions
            shall have the same meaning regardless of whether they appear in
            singular or in plural.
          </p>
          <h3>Definitions</h3>
          <p>For the purposes of this Privacy Policy:</p>
          <ul>
            <li>
              <strong>You</strong> means the individual accessing or using the
              Service, or the company, or other legal entity on behalf of which
              such individual is accessing or using the Service, as applicable.
            </li>
            <li>
              <strong>Account</strong> means a unique account created for You to
              access our Service or parts of our Service.
            </li>
            <li>
              <strong>Company</strong> (referred to as either "the Company",
              "We", "Us" or "Our" in this Agreement) refers to Zenerate Inc.,
              555 West 5th Street, 35th Floor, Los Angeles CA 90013.
            </li>
            <li>
              <strong>Cookies</strong> are small files that are placed on Your
              computer, mobile device or any other device by a website,
              containing the details of Your browsing history on that website
              among its many uses.
            </li>
            <li><strong>Country</strong> refers to: Delaware, United States</li>
            <li>
              <strong>Device</strong> means any device that can access the
              Service such as a computer, a mobile device or a digital tablet.
            </li>
            <li>
              <strong>Personal Data</strong> is any information that relates to
              an identified or identifiable individual.
            </li>
            <li>
              <strong>Service</strong> refers to any other related services
              provided by Zenerate Inc through Zenerate Website, accessible from
              http://zenerate.ai and Zenerate App, accessible from
              http://app.zenerate.ai
            </li>
            <li>
              <strong>Service Provider</strong> means any natural or legal
              person who processes the data on behalf of the Company. It refers
              to third-party companies or individuals employed by the Company to
              facilitate the Service, to provide the Service on behalf of the
              Company, to perform services related to the Service or to assist
              the Company in analyzing how the Service is used.
            </li>
            <li>
              <strong>Usage Data</strong> refers to data collected
              automatically, either generated by the use of the Service or from
              the Service infrastructure itself (for example, the duration of a
              page visit).
            </li>
          </ul>

          <h2>Personal Information We Collect</h2>
          <h3>Types of Data Collected</h3>
          <h4>Personal Data</h4>
          <p>
            While using Our Service, We may ask you to provide Us with certain
            personally identifiable information that can be used to contact or
            identify You. Personally identifiable information may include, but
            is not limited to:
          </p>
          <ul>
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Company</li>
            <li>Job</li>
            <li>Usage Data</li>
          </ul>

          <h4>Usage Data</h4>
          <p>Usage Data is collected automatically when using the Service.</p>
          <p>
            Usage Data may include information such as Your Device's Internet
            Protocol address (e.g. IP address), browser type, browser version,
            the pages of our Service that You visit, the time and date of Your
            visit, the time spent on those pages, unique device identifiers and
            other diagnostic data.
          </p>
          <p>
            When You access the Service by or through a mobile device, We may
            collect certain information automatically, including, but not
            limited to, the type of mobile device You use, Your mobile device
            unique ID, the IP address of Your mobile device, Your mobile
            operating system, the type of mobile Internet browser You use,
            unique device identifiers and other diagnostic data.
          </p>
          <p>
            We may also collect information that Your browser sends whenever You
            visit our Service or when You access the Service by or through a
            mobile device.
          </p>
          <h4>Tracking Technologies and Cookies</h4>
          <p>
            We use Cookies and similar tracking technologies to track the
            activity on Our Service and store certain information. Tracking
            technologies used are tags, and scripts to collect and track
            information and to improve and analyze Our Service. The technologies
            We use may include:
          </p>
          <ul>
            <li>
              <p>
                <strong>Cookies or Browser Cookies.</strong> A cookie is a small
                file placed on Your Device. You can instruct Your browser to
                refuse all Cookies or to indicate when a Cookie is being sent.
                However, if You do not accept Cookies, You may not be able to
                use some parts of our Service. Unless you have adjusted Your
                browser setting so that it will refuse Cookies, our Service may
                use Cookies.
              </p>
            </li>
          </ul>
          <p>
            Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies
            remain on Your personal computer or mobile device when You go
            offline, while Session Cookies are deleted as soon as You close Your
            web browser. Learn more about cookies: Cookies by PrivacyPolicies
            Generator.
          </p>
          <p>
            We use both Session and Persistent Cookies for the purposes set out
            below:
          </p>
          <ul>
            <li>
              <p>
                <span>Name : 1P_JAR</span>
                <span>Provider : .gstatic.com </span>
                <span
                  >Purpose & Service : This group sets a unique ID to remember
                  your preferences and other information such as website
                  statistics and track conversion rates. Google’s policies can
                  be viewed at
                  <a href="https://policies.google.com/technologies/types"
                    >https://policies.google.com/technologies/types
                  </a>
                </span>
                <span>Expiry : Various</span>
              </p>
            </li>
            <li>
              <p>
                <span>Name : _gat#</span>
                <span>Provider : .zenerate.ai </span>
                <span
                  >Purpose & Service : Enables Google Analytics to regulate the
                  rate of requesting. It is a HTTP cookie type that lasts for a
                  session. Google Analytics
                  <a href="https://policies.google.com/technologies/ads"
                    >View Service Privacy Policy
                  </a>
                </span>
                <span>Country : United States</span>
                <span>Type : http_cookie</span>
                <span>Expires_in : 1 minute.</span>
              </p>
            </li>
            <li>
              <p>
                <span>Name : _ga</span>
                <span>Provider : .zenerate.ai </span>
                <span
                  >Purpose & Service : It records a particular ID used to come
                  up with data about website usage by the user. It is a HTTP
                  cookie that expires after 2 years. Google Analytics
                  <a href="https://policies.google.com/technologies/ads"
                    >View Service Privacy Policy
                  </a>
                </span>
                <span>Country : United States </span>
                <span>Type : http_cookie </span>
                <span>Expires_in : 1 year 11 months 29 day </span>
              </p>
            </li>
            <li>
              <p>
                <span>Name : _gid</span>
                <span>Provider : .zenerate.ai </span>
                <span
                  >Purpose & Service : Keeps an entry of unique ID which is then
                  used to come up with statistical data on website usage by
                  visitors. It is a HTTP cookie type and expires after browsing
                  session. Google Analytics
                  <a href="https://policies.google.com/technologies/ads"
                    >View Service Privacy Policy
                  </a>
                </span>
                <span>Country : United States</span>
                <span>Type : http_cookie</span>
                <span>Expires_in : 1 day</span>
              </p>
            </li>
            <li>
              <p>
                <span>Name : _gat</span>
                <span>Provider : .zenerate.ai </span>
                <span
                  >Purpose & Service : Used to monitor the number of Google
                  Analytics server requests when using Google Tag Manager.
                  Google Analytics
                  <a href="https://policies.google.com/technologies/ads"
                    >View Service Privacy Policy
                  </a>
                </span>
                <span>Country : United States</span>
                <span>Type : http_cookie</span>
                <span>Expires_in : 1 minute</span>
              </p>
            </li>
          </ul>

          <h2>Using Your Personal Information</h2>
          <p>The Company may use Personal Data for the following purposes:</p>
          <ul>
            <li>
              <strong>To provide and maintain our Service</strong>, including to
              monitor the usage of our Service.
            </li>
            <li>
              <strong>To manage Your Account:</strong> to manage Your
              registration as a user of the Service. The Personal Data You
              provide can give You access to different functionalities of the
              Service that are available to You as a registered user.
            </li>
            <li>
              <strong>For the performance of a contract:</strong> the
              development, compliance and undertaking of the purchase contract
              for the products, items or services You have purchased or of any
              other contract with Us through the Service.
            </li>
            <li>
              <strong>To contact You:</strong> To contact You by email,
              telephone calls, SMS, or other equivalent forms of electronic
              communication, such as a mobile application's push notifications
              regarding updates or informative communications related to the
              functionalities, products or contracted services, including the
              security updates, when necessary or reasonable for their
              implementation.
            </li>
            <li>
              <strong>To provide You</strong> with news, special offers and
              general information about other goods, services and events which
              we offer that are similar to those that you have already purchased
              or enquired about unless You have opted not to receive such
              information.
            </li>
            <li>
              <strong>To manage Your requests:</strong> To attend and manage
              Your requests to Us.
            </li>
            <li>
              <strong>For business transfers:</strong>
              We may use Your information to evaluate or conduct a merger,
              divestiture, restructuring, reorganization, dissolution, or other
              sale or transfer of some or all of Our assets, whether as a going
              concern or as part of bankruptcy, liquidation, or similar
              proceeding, in which Personal Data held by Us about our Service
              users is among the assets transferred.
            </li>
            <li>
              <strong>For other purposes:</strong> We may use Your information
              for other purposes, such as data analysis, identifying usage
              trends, determining the effectiveness of our promotional campaigns
              and to evaluate and improve our Service, products, services,
              marketing and your experience.
            </li>
          </ul>

          <h2>Sharing Your Personal Information</h2>
          <p>
            The Company may process of share your data that we hold based on the
            following legal basis: More specifically, we may need to process
            your data or share your personal information in the following
            situations:
          </p>
          <ul>
            <li>
              <strong>Business Transfers</strong>
              We may share or transfer your information in connection with, or
              during negotiations of, any merger, sale of company assets,
              financing, or acquisition of all or a portion of our business to
              another company.
            </li>
            <li>
              <strong>Affiliates</strong>
              We may share your information with our affiliates, in which case
              we will require those affiliates to honor this privacy notice.
              Affiliates include our parent company and any subsidiaries, joint
              venture partners or other companies that we control or that are
              under common control with us.
            </li>
            <li>
              <strong>Business Partners</strong>
              We may share your information with our business partners to offer
              you certain products, services or promotions.
            </li>
          </ul>

          <p>
            We do not sell your personal information for the intents and
            purposes of the California Consumer Privacy Act (CCPA).
          </p>

          <h2>Data Subject Rights</h2>
          <p>
            You have rights concerning Your personal data. For all such Personal
            Data, you may exercise your rights by contacting us as stated below.
            If You wish to exercise Your privacy rights under applicable law
            (including the EU or UK GDPR or the California Consumer Privacy Act
            (CCPA)), such as the right to request access to, rectification or
            erasure of Your personal data held with Us, or to restrict or object
            to such personal data’s processing, or to obtain a copy or port such
            personal data (each to the extent available to You under the laws
            which apply to You) – please contact us by e-mail at
            <a href="mailto:contact@zenerate.ai">contact@zenerate.ai </a>
          </p>

          <h2>Children</h2>
          <p>
            Our Service does not address anyone under the age of 13. We do not
            knowingly collect personally identifiable information from anyone
            under the age of 13. If You are a parent or guardian and You are
            aware that Your child has provided Us with Personal Data, please
            contact Us. If We become aware that We have collected Personal Data
            from anyone under the age of 13 without verification of parental
            consent, We take steps to remove that information from Our servers.
          </p>
          <p>
            If We need to rely on consent as a legal basis for processing Your
            information and Your country requires consent from a parent, We may
            require Your parent's consent before We collect and use that
            information.
          </p>

          <h2>Change</h2>
          <p>
            We may update Our Privacy Policy from time to time. We will notify
            You of any changes by posting the new Privacy Policy on this page.
          </p>
          <p>
            We will let You know via email and/or a prominent notice on Our
            Service, prior to the change becoming effective and update the "Last
            updated" date at the top of this Privacy Policy.
          </p>
          <p>
            You are advised to review this Privacy Policy periodically for any
            changes. Changes to this Privacy Policy are effective when they are
            posted on this page.
          </p>

          <h2>Contact Us</h2>
          <p>
            If you have any questions or concerns regarding our privacy policy,
            please contact us at
            <a href="mailto:contact@zenerate.ai">contact@zenerate.ai </a>
          </p>
        </div>
      </div>

      <i class="scroll-to-top" @click="($evt) => scollToTop()">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
          fill="#000000"
        >
          <path d="M0 0h24v24H0V0z" fill="none" />
          <path
            d="M4 12l1.41 1.41L11 7.83V20h2V7.83l5.58 5.59L20 12l-8-8-8 8z"
          />
        </svg>
      </i>

      <div class="section section-footer fp-auto-height-responsive">
        <Footer></Footer>
      </div>
    </div>
  </div>
</template>
<script lang="ts" setup>
import { ref, onMounted, onBeforeUnmount, computed } from 'vue'
import Store from '/Store/index'
import Footer from '/Components/Footer.vue'

const fullpage = computed(() => Store.state.root.FullPage)

onMounted(() => {
  fullpage.value.destroy()
})

const scollToTop = () => {
  const el = document.querySelector('.inner-contents')
  el.scrollIntoView({ behavior: 'smooth', block: 'start' })
}
</script>
<style lang="scss" scoped>
#fullpage-private {
  overflow: hidden;
  .section-inner {
    @include flex;
    position: relative;
    height: 100%;
    padding: 0px 60px;
    cursor: default;

    @include en-tablet {
      padding: 0px 24px;
      max-width: 100%;
    }
    @include en-mobile {
      padding: 0 24px;
      max-width: 100%;
    }
  }
}

.scroll-to-top {
  @include fixed(bottom 24px right 32px);
  cursor: pointer;
  z-index: 9;

  svg {
    width: 40px;
    height: 40px;

    fill: $text-darken;
  }

  @include en-mobile {
    @include fixed(bottom 14px right 18px);
    svg {
      width: 32px;
      height: 32px;
    }
  }
}

.inner-contents {
  padding-top: 140px;
  padding-bottom: 60px;
  height: content-fit;
  text-align: left;
}

h1 {
  @include medium(36);
  margin: 0px 0px 48px 0px;
  padding: 0px;
  color: #161616;
  @include en-mobile {
    @include medium(28);
    margin: 0px 0px 28px 0px;
  }
}

h2 {
  @include bold(22);
  margin: 0px 0px 28px 0px;
  padding: 0px;
  color: #161616;
  @include en-mobile {
    @include bold(18);
    margin: 0px 0px 16px 0px;
  }
}

h3 {
  @include bold(18);
  margin: 0px 0px 28px 0px;
  padding: 0px;
  color: #161616;
  @include en-mobile {
    @include bold(16);
    margin: 0px 0px 16px 0px;
  }
}

ul {
  margin-bottom: 28px;
  @include en-mobile {
    margin-bottom: 16px;
  }

  li {
    @include regular(16);
    margin: 0px 0px 14px 20px;
    list-style-type: disc;
    color: #707070;

    @include en-mobile {
      @include regular(14);
      margin: 0px 0px 12px 16px;
    }
  }
}

p {
  @include regular(16);
  margin-bottom: 20px;
  line-height: 20px;
  color: #707070;
  @include en-mobile {
    @include regular(14);
    margin: 0px 0px 16px 0px;
  }
}

span {
  display: block;
  margin-bottom: 4px;

  &.core-text {
    color: #5c6dff;
  }
}

a,
a:hover,
a:active,
a:visited {
  text-decoration: underline;
  color: #5c6dff;
}
</style>
